module.exports.descriptors = [
    'Great',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
    'Grand',
    'Barren',
    'Rocky',
    'Low',
    'High',
    'White Cloud',
    'Rough',
    'Little',
    'Quiet',
    'Castle',
    'Timber'
]

module.exports.places = [
    'Flats',
    'Valley',
    'Canyon',
    'Pond',
    'Forest',
    'Mountains',
    'Plains',
    'Camp',
    'Swamp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Lake',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
    'Desert',
    'Wetlands',
    'Park',
    'State Park',
    'National Park',
    'Volcanic Fields',
    'National Forest',
    'Wilderness',
    'Rainforest',
    'Fields'
]
